//! An intrusive red-black tree API, in the style of the Linux kernel's
//! `struct rb_node` + `container_of()`.
//!
//! [`Link`] carries no data and no allocation of its own: it is embedded as
//! a plain field inside a caller-defined struct (even more than once, for
//! membership in more than one tree), and an [`Adapter`] is generated by
//! [`crate::intrusive_adapter!`] and converts between a `Link` pointer and a
//! pointer to the struct that embeds it.
mod adapter;
mod link;

pub use adapter::Adapter;
pub use link::Link;
