# frozen_string_literal: true

require "bundler/gem_tasks"
require "rake/testtask"
require "rb_sys/extensiontask"
require "rubocop/rake_task"

task default: %i[compile rubocop]
task build: :compile

spec = Gem::Specification.load("rougenoir_ruby.gemspec")

# spec.requirements.clear
# spec.required_ruby_version = nil
# spec.required_rubygems_version = nil
# spec.extensions.clear
# spec.files -= Dir["ext/**/*"]

RbSys::ExtensionTask.new("rougenoir_ruby", spec) do |ext|
  ext.lib_dir = "lib/rougenoir_ruby"

  ext.cross_compile = true
  # ext.cross_platform = %w[
  #   aarch64-linux
  #   arm64-darwin
  #   x64-mingw-ucrt
  #   x64-mingw32
  #   x86_64-darwin
  #   x86_64-linux
  #   x86_64-linux-musl
  # ]
end

test_files = FileList[File.expand_path("test/**/*_test.rb", __dir__)]

Rake::TestTask.new do |t|
  t.deps << :compile
  t.test_files = test_files
end

if RUBY_PLATFORM =~ /linux/i
  require "ruby_memcheck"
  namespace :test do
    test_config = lambda do |t|
      t.libs << "test"
      t.test_files = test_files
    end
    RubyMemcheck::TestTask.new(valgrind: :compile, &test_config)
  end
end

RuboCop::RakeTask.new

desc "Open console with extension loaded"
task console: :compile do
  exec "irb -r ./lib/rougenoir_ruby"
end

# desc "Run benchmarks"
# task bench: :compile do
#   ruby "benchmark/run.rb"
# end
